# Generated by Django 3.2.8 on 2021-10-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211022_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
